STRATEGIES = [
    {
        "id": "1",
        "name": "Monday SPX Calendar",
        "DayOfWeek": "Monday",
        "Delta": 70,
        "D1": 4,
        "D2": 6,
        "T1": "09:32",
        "T2": "15:30",
        "TP": 20,
        "MaxCost": 10000,
        "Vix": [10, 30],
        "VixOvernightRange": [-5, 5],
        "VixIntradayRange": [-3, 3],
        "AveragingDropPct": 10,
        "AveragingTimes": ["10:00", "11:00"],
        "AveragingAmount": 2000
    },
    {
        "id": "2",
        "name": "Wednesday SPX Calendar",
        "DayOfWeek": "Wednesday",
        "Delta": 65,
        "D1": 2,
        "D2": 7,
        "T1": "10:00",
        "T2": "15:00",
        "TP": 15,
        "MaxCost": 8000,
        "Vix": [12, 28],
        "VixOvernightRange": [-4, 4],
        "VixIntradayRange": [-2, 2],
        "AveragingDropPct": 8,
        "AveragingTimes": ["11:00", "12:00"],
        "AveragingAmount": 1500
    },
    {
        "id": "3",
        "name": "Saturday Test",
        "DayOfWeek": "Saturday",
        "Delta": 70,
        "D1": 4,
        "D2": 6,
        "T1": "13:00",
        "T2": "15:30",
        "TP": 20,
        "MaxCost": 10000,
        "Vix": [10, 30],
        "VixOvernightRange": [-5, 5],
        "VixIntradayRange": [-3, 3],
        "AveragingDropPct": 10,
        "AveragingTimes": ["13:30"],
        "AveragingAmount": 2000
    }
]